# Generated by Django 5.0.3 on 2024-04-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_comm',
            field=models.DateField(auto_now=True),
        ),
    ]
