# Generated by Django 5.0.3 on 2024-04-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_rename_id_client_client_id'),
        ('Commande', '0002_alter_commande_date_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=1000000, default=0, max_digits=10000000),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Clients.client'),
        ),
    ]
