# Generated by Django 5.0.3 on 2024-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0003_commande_montant_total_alter_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
