# Generated by Django 5.0.3 on 2024-04-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_client_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id_client',
            new_name='id',
        ),
    ]
