# Generated by Django 5.0.3 on 2024-04-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('Id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorie.categorie')),
            ],
        ),
    ]
