# Generated by Django 5.0.3 on 2024-04-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='Id_produit',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='nom_prod',
            new_name='title',
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
